### ISSUE TITLE
robot drivers

### ISSUE THREAD

**Issue by DavidFerreira1002** [DavidFerreira1002/RC_Project#17]
work on the robot drivers

**Comment by ISeaFood30** [comment]
para alem do srobot drivers, criar a possibilidade de escolha de modo simulaçao ou robo real

**Comment by Lacerda111** [comment]
foi preciso instalar libuvc-dev

**Comment by Lacerda111** [comment]
e instalar sudo apt install libaria-dev

**Comment by ISeaFood30** [comment]
sudo adduser user dialout
depois fazer log out e log in / restart da vm
quando em duvida pedir ajuda a alguem para que isto funcione sem se mudar nada

**Comment by ISeaFood30** [comment]
quando usamos o robo o use_sim_time tem que ser false

**Comment by ISeaFood30** [comment]
tentamos usar um comando xbox, nao funciona o BT
