### ISSUE TITLE
Manual AND automatic exploration

### ISSUE THREAD

**Issue by ISeaFood30** [DavidFerreira1002/RC_Project#19]
colocar uma possibilidade de entrar no modo de exploracao sendo o modo automatico ou com o teleop_key

**Comment by ISeaFood30** [comment]
testar correr, fechar o teleop, matar ficheiro, e depois correr o navigation.
e rezar que funcione

**Comment by Lacerda111** [comment]
quando se for ao lab: confirmar se se pode ter o nodo de teleop no mesmo terminal que o exploration_real
